apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-config
  namespace: chest-xray-mlops
data:
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "mlops"
  MINIO_ENDPOINT: "minio-service:9000"
  MLFLOW_TRACKING_URI: "http://mlflow-service:5000"
  MODEL_REGISTRY_URL: "http://model-registry-service:8003"
  DEPLOYMENT_URL: "http://deployment-service:8004"